const AUTHENTICATION_CHALLENGE_TTL_MS = 10 * 60 * 1_000;
export const MAGIC_LINK_TTL_MS = AUTHENTICATION_CHALLENGE_TTL_MS;
export const PENDING_GOOGLE_LINK_TTL_MS = AUTHENTICATION_CHALLENGE_TTL_MS;
export const GOOGLE_TRANSACTION_TTL_MS = AUTHENTICATION_CHALLENGE_TTL_MS;
export const AUTHENTICATION_CHALLENGE_COOKIE_MAX_AGE_MS =
  AUTHENTICATION_CHALLENGE_TTL_MS;
