import {
  AUTHENTICATION_RATE_LIMIT,
  AUTHENTICATION_RATE_LIMIT_WINDOW_MS,
} from './rate-limit.constants';

export const PENDING_GOOGLE_LINK_RATE_LIMIT = AUTHENTICATION_RATE_LIMIT;
export const PENDING_GOOGLE_LINK_RATE_LIMIT_WINDOW_MS =
  AUTHENTICATION_RATE_LIMIT_WINDOW_MS;
export const PENDING_GOOGLE_LINK_RATE_LIMIT_KEY_PREFIX =
  'pending-google-link:user:';
export const PENDING_GOOGLE_LINK_CLEANUP_BATCH_SIZE = 100;
export const PENDING_GOOGLE_LINK_TERMINAL_RETENTION_MS = 0;
