export const EMAIL_DELIVERY_SUCCEEDED = 'EMAIL_DELIVERY_SUCCEEDED';
export const EMAIL_DELIVERY_FAILED = 'EMAIL_DELIVERY_FAILED';
export const EMAIL_CHALLENGE_REVOKED = 'EMAIL_CHALLENGE_REVOKED';
export const EMAIL_CHALLENGE_REVOCATION_SKIPPED =
  'EMAIL_CHALLENGE_REVOCATION_SKIPPED';
export const EMAIL_CHALLENGE_REVOCATION_FAILED =
  'EMAIL_CHALLENGE_REVOCATION_FAILED';
export const EMAIL_UNKNOWN_PROVIDER_FAILURE = 'PROVIDER_UNAVAILABLE';
export const EMAIL_REVOCATION_FAILED = 'REVOCATION_FAILED';
export const EMAIL_CHALLENGE_STATE_CHANGED = 'CHALLENGE_STATE_CHANGED';
