import type { AuthenticationErrorCode } from '../../domain/errors/authentication.error';

export const AUTHENTICATION_PUBLIC_ERROR_CODES: Readonly<
  Record<AuthenticationErrorCode, string>
> = {
  INVALID_INPUT: 'AUTH_FAILED',
  EMAIL_ALREADY_EXISTS: 'AUTH_FAILED',
  INVALID_CREDENTIAL: 'AUTH_FAILED',
  ACCOUNT_INACTIVE: 'AUTH_FAILED',
  CHALLENGE_INVALID: 'AUTH_FAILED',
  OAUTH_INVALID: 'AUTH_GOOGLE_UNAVAILABLE',
  ACCOUNT_LINKING_REQUIRED: 'AUTH_LINKING_REQUIRED',
  SESSION_INVALID: 'AUTH_FAILED',
  SESSION_REPLAY: 'AUTH_FAILED',
  CSRF_INVALID: 'AUTH_CSRF_REJECTED',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
  PROVIDER_UNAVAILABLE: 'AUTH_GOOGLE_UNAVAILABLE',
};
